name: HTTP Trigger

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Response to Webhook event
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: |
          python weread2opml.py $MESSAGE
